inherit_from: ../.rubocop.yml

require:
  - rubocop/cop/internal_affairs
  - rubocop-rspec

inherit_gem:
  my-shared-gem:
    - default.yml
    - strict.yml
    
inherit_gem:
  my-shared-gem: .rubocop.yml
  cucumber: conf/rubocop.yml

AllCops:
  DisabledByDefault: true

Security/MarshalLoad:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Performance/HashEachMethods:
  Enabled: true
